version: '3'
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #      MONGO_INITDB_DATABASE: popular_articles
    networks:
      - e2e

  kafka:
    image: landoop/fast-data-dev:2.3.1
    restart: always
    environment:
      ADV_HOST: kafka
      RUNTESTS: 0
      FORWARDLOGS: 0
      SAMPLEDATA: 0
    ports:
      - 2181:2181
      - 3030:3030
      - 8081:8081
      - 8082:8082
      - 9092:9092
    networks:
      - e2e

networks:
  e2e: { }



