version: '3'
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:4.4
    ports:
    - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: popular_articles
    networks:
    - e2e

networks:
  e2e: {}



